"""Character dataclass and PNG card loader."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from pathlib import Path

import tomllib

from ara.llm.context import ConversationContext
from ara.memory.chroma import ChromaStore
from ara.memory.knowledge import CharacterMemory, NullMemory, Scratchpad
from ara.models import Context, Importance
from ara.utils.logger import get_logger

logger = get_logger(__name__)


def _stable_uuid(name: str) -> uuid.UUID:
    """Generate a deterministic UUID for *name*.

    :param name: Character name.
    :return: Stable UUID5 derived from a fixed namespace.
    """
    return uuid.uuid5(uuid.NAMESPACE_DNS, f"ara.character.{name}")


@dataclass
class Character:
    """In-world character backed by a card and persistent memory.

    :ivar id: Stable UUID derived from the character's name.
    :ivar name: Display name.
    :ivar card_fields: Key-value pairs loaded from the PNG card metadata.
    :ivar importance: Persistence level controlling scratch updates and
        memory storage.
    :ivar memory: Vector-backed conversation memory.
    :ivar scratch: Ephemeral scratchpad for in-scene reasoning.
    :ivar sprites: List of available sprite names (filename stems) for this
        character, e.g. ``["default_neutral", "default_happy"]``.
    :ivar current_sprite: The sprite currently being displayed.
    :ivar crops: Per-sprite crop regions keyed by sprite name.
    """

    id: uuid.UUID
    name: str
    card_fields: dict[str, str]
    importance: Importance
    memory: CharacterMemory | NullMemory
    scratch: Scratchpad
    sprites: list[str] = field(default_factory=list)
    current_sprite: str = ""
    crops: dict[str, dict[str, Any]] = field(default_factory=dict)
    prev_scene_summary: str = ""
    """Tailored bridging summary injected at the start of a new scene."""

    @property
    def whoami(self) -> Context:
        """Return injected context that establishes the character's identity.

        The context follows a question-and-answer format where the model is
        prompted for each card field and supplies the stored value.
        """
        name = self.name
        fields = [
            ("name", name),
            ("summary", self.card_fields.get("summary", "")),
            ("personality", self.card_fields.get("personality", "")),
            ("scenario", self.card_fields.get("scenario", "")),
            ("greeting_message", self.card_fields.get("greeting_message", "")),
            ("example_messages", self.card_fields.get("example_messages", "")),
        ]
        ctx: Context = []
        for field_name, value in fields:
            ctx.append({
                "role": "user",
                "content": f"Please provide your `{field_name}`.",
                "name": ConversationContext.default_sysname,
            })
            ctx.append({
                "role": "assistant",
                "content": value,
                "name": name,
            })
        return ctx

    @property
    def scene_summary_context(self) -> Context:
        """Return a context snippet that injects the per-character scene summary.

        This is generated by the Summarizer during scene transitions and
        tells the character what they should remember from the previous scene.
        """
        if not self.prev_scene_summary:
            return []
        return [
            {
                "role": "user",
                "content": "Please summarize what happened before this scene.",
                "name": ConversationContext.default_sysname,
            },
            {
                "role": "assistant",
                "content": self.prev_scene_summary,
                "name": self.name,
            },
        ]

    @property
    def scratch_context(self) -> Context:
        """Return a context snippet that injects the character's scratchpad.

        If the scratch is still at its default, the previous scene's scratch
        is shown instead so the character retains continuity.
        """
        empty = self.scratch.text == "Nothing yet!"
        if not empty:
            user_content = (
                "Please provide your `scratch`.\n"
                "Never show this to others, or mention that it exists!"
            )
            assistant_content = self.scratch.text
        else:
            user_content = (
                "Please provide the summary of your `scratch` "
                "from your previous conversation.\n"
                "Never show this to others, or mention that it exists!"
            )
            assistant_content = self.scratch.prev_text

        return [
            {
                "role": "user",
                "content": user_content,
                "name": ConversationContext.default_sysname,
            },
            {
                "role": "assistant",
                "content": assistant_content,
                "name": self.name,
            },
        ]

    def __hash__(self) -> int:
        return hash(self.id)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Character):
            return NotImplemented
        return self.id == other.id

    def __repr__(self) -> str:
        return f"<Character {self.name}>"


def _read_meta(path: Path) -> dict[str, str]:
    """Read an optional ``meta.toml`` sidecar from *path*.

    :param path: Directory that may contain ``meta.toml``.
    :return: Parsed TOML dict or an empty dict if the file does not exist.
    """
    meta_path = path / "meta.toml"
    if meta_path.exists():
        with meta_path.open("rb") as f:
            return tomllib.load(f)
    return {}


def _read_card_toml(path: Path) -> dict[str, str] | None:
    """Read an optional ``card.toml`` sidecar from *path*.

    :param path: Character asset directory.
    :return: Parsed card fields, or ``None`` if the file does not exist.
    """
    card_path = path / "card.toml"
    if card_path.exists():
        with card_path.open("rb") as f:
            data = tomllib.load(f)
        return {
            "name": data.get("name", ""),
            "summary": data.get("summary", ""),
            "personality": data.get("personality", ""),
            "scenario": data.get("scenario", ""),
            "greeting_message": data.get("greeting_message", ""),
            "example_messages": data.get("example_messages", ""),
        }
    return None


def create_anonymous_character(
    name: str,
    description: str = "",
    sprite: str = "",
) -> Character:
    """Create a background extra with no assets and no persistent memory.

    :param name: Display name for the background character.
    :param description: Unstructured description of what the character is and
        should do. Stored in ``card_fields["summary"]`` so it appears in the
        character's ``whoami`` context.
    :param sprite: Sprite identifier for the web VN frontend (e.g.
        ``cat_neutral``). Resolved under ``data/assets/cc/anonymous/``.
    :return: A :class:`Character` with :attr:`Importance.ANONYMOUS`.
    """
    char_id = _stable_uuid(name)
    return Character(
        id=char_id,
        name=name,
        card_fields={
            "name": name,
            "summary": description,
            "personality": "",
            "scenario": "",
            "greeting_message": "",
            "example_messages": "",
            "sprite": sprite,
        },
        importance=Importance.ANONYMOUS,
        memory=NullMemory(),
        scratch=Scratchpad(),
        sprites=[],
        current_sprite="",
    )


def load_character(path: Path, db: ChromaStore) -> Character:
    """Load a character from a directory containing a ``card.toml`` sidecar.

    The directory may also contain PNG sprites and a ``meta.toml`` file with
    an ``importance`` key (one of ``ANONYMOUS``, ``IMPORTANT``, ``REQUIRED``
    or ``EIGEN``).

    :param path: Character asset directory.
    :param db: Shared ChromaDB store.
    :return: Fully initialised :class:`Character`.
    :raises RuntimeError: If no ``card.toml`` is found.
    """
    pngs = list(path.glob("*.png"))
    card_toml = _read_card_toml(path)

    if card_toml is None:
        raise RuntimeError(f"No card.toml found in {path}")

    name = card_toml["name"] or path.name
    card_fields = card_toml

    meta = _read_meta(path)
    importance_name = meta.get("importance", "ANONYMOUS")
    importance = Importance.__members__.get(importance_name, Importance.ANONYMOUS)

    # Parse per-sprite crop regions from meta.toml (e.g. [default_neutral] topleft = [0,0])
    crops: dict[str, dict[str, Any]] = {}
    for key, value in meta.items():
        if key in ("importance", "sprites", "default_sprite"):
            continue
        if isinstance(value, dict) and "topleft" in value and "bottomright" in value:
            crops[key] = {
                "topleft": value["topleft"],
                "bottomright": value["bottomright"],
            }

    char_id = _stable_uuid(name)

    # Sprite list: explicit meta.toml ``sprites`` array, or discover PNGs.
    sprites = meta.get("sprites")
    if not sprites:
        sprites = [f.stem for f in path.glob("*.png")]
    current_sprite = meta.get("default_sprite", sprites[0] if sprites else "")

    logger.debug(f"Loaded character {card_fields['name']} (importance={importance_name})")
    return Character(
        id=char_id,
        name=card_fields["name"],
        card_fields=card_fields,
        importance=importance,
        memory=CharacterMemory(character_id=char_id, db=db),
        scratch=Scratchpad(),
        sprites=sprites,
        current_sprite=current_sprite,
        crops=crops,
    )
